[package]
name = "rose"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
spin = { version = "0.10.0", features = ["lazy", "rwlock"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
